import React, { useState } from 'react';
import { Download, ShieldAlert, FileText, Share2, Clipboard, Loader2, CheckCircle2, AlertCircle, Cpu, FlaskConical, Search, Check, Microscope, RotateCcw, ChevronRight } from 'lucide-react';
import { testHypothesis } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'motion/react';

interface ReportingDeckProps {
  graph: {
    nodes: any[];
    links: any[];
    narrative?: string;
  };
  projectName: string;
  onExpand?: () => void;
  isExpanding?: boolean;
  autoGrow?: boolean;
  onToggleAutoGrow?: (val: boolean) => void;
  handleDownloadBackup?: () => void;
  onVeniceSensemaking?: () => void;
  isVeniceLoading?: boolean;
}

export default function ReportingDeck({ graph, projectName, onExpand, isExpanding, autoGrow, onToggleAutoGrow, handleDownloadBackup, onVeniceSensemaking, isVeniceLoading }: ReportingDeckProps) {
  const [error, setError] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);
  const [hypothesis, setHypothesis] = useState('');
  const [isTestingHypothesis, setIsTestingHypothesis] = useState(false);
  const [hypothesisResult, setHypothesisResult] = useState<string | null>(null);

  if (!graph || !graph.nodes) {
    return (
      <div className="p-10 text-center opacity-20">
        <p className="text-[10px] font-mono uppercase">Initializing Intel Engine...</p>
      </div>
    );
  }

  const safeProjectName = projectName || 'Unnamed Investigation';

  const exportToJson = () => {
    try {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(graph, null, 2));
      const downloadAnchorNode = document.createElement('a');
      downloadAnchorNode.setAttribute("href", dataStr);
      downloadAnchorNode.setAttribute("download", `${safeProjectName.replace(/\s+/g, '_')}_nexus_export.json`);
      document.body.appendChild(downloadAnchorNode);
      downloadAnchorNode.click();
      downloadAnchorNode.remove();
    } catch (err) {
      console.error("Export failed", err);
      setError("Failed to export JSON");
    }
  };

  const exportToCsv = () => {
    try {
      const headers = ['id', 'name', 'type', 'description'];
      const rows = (graph.nodes || []).map(n => [n.id, n.name || '', n.type || '', n.description || ''].map(v => `"${v}"`).join(','));
      const csvContent = "data:text/csv;charset=utf-8," + headers.join(',') + "\n" + rows.join('\n');
      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", `${safeProjectName.replace(/\s+/g, '_')}_evidence_matrix.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      console.error("CSV Export failed", err);
      setError("Failed to export CSV");
    }
  };

  const handleTestHypothesis = async () => {
    if (!hypothesis.trim()) return;
    setIsTestingHypothesis(true);
    setHypothesisResult(null);
    setError(null);
    try {
      const contextNodes = (graph.nodes || []).map(n => n.name || n.id);
      const result = await testHypothesis(hypothesis, contextNodes);
      setHypothesisResult(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsTestingHypothesis(false);
    }
  };

  const copyMarkdownDossier = () => {
    try {
      const md = `
# INVESTIGATIVE DOSSIER: ${safeProjectName}
## Intelligence Summary
${graph.narrative || 'No narrative generated.'}

## Entity Lattice
### Nodes (${(graph.nodes || []).length})
${(graph.nodes || []).map(n => `- **${n.name || n.id}** (${n.type}): ${n.description || 'No description available.'}`).join('\n')}

### Relationships (${(graph.links || []).length})
${(graph.links || []).map(l => `- ${l.source} → ${l.target} [${l.relationship || 'Connected'}]`).join('\n')}

---
*Generated by Nexus Narrative Explorer*
      `.trim();

      navigator.clipboard.writeText(md);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Copy failed", err);
      setError("Failed to copy dossier");
    }
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3">
        <button
          onClick={exportToJson}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-all hover:border-green-500/30 group"
        >
          <Share2 className="text-white/40 group-hover:text-green-500 mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/60">JSON Export</span>
        </button>

        <button
          onClick={exportToCsv}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-all hover:border-green-500/30 group"
        >
          <Download className="text-white/40 group-hover:text-green-500 mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/60">CSV Matrix</span>
        </button>

        <button
          onClick={copyMarkdownDossier}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/5 border border-white/10 hover:bg-white/10 transition-all hover:border-green-500/30 group"
        >
          {copySuccess ? (
            <CheckCircle2 className="text-green-500 mb-2" size={20} />
          ) : (
            <Clipboard className="text-white/40 group-hover:text-green-500 mb-2" size={20} />
          )}
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/60">MD Dossier</span>
        </button>



        <button
          onClick={handleDownloadBackup}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-green-500/10 border border-green-500/20 hover:bg-green-500/20 transition-all hover:border-green-500 group"
        >
          <RotateCcw className="text-green-500 mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-green-500">Local Archive</span>
        </button>
      </div>

      <div className="p-1 rounded-2xl bg-gradient-to-r from-blue-600/20 via-purple-600/20 to-green-600/20 relative overflow-hidden group">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 via-purple-500/10 to-green-500/10 opacity-0 group-hover:opacity-100 transition-opacity" />
        <button
          onClick={onVeniceSensemaking}
          disabled={isVeniceLoading}
          className="w-full relative flex items-center justify-between p-4 bg-[#0a0a0a] rounded-xl border border-white/5 hover:border-white/10 transition-colors disabled:opacity-50"
        >
          <div className="flex items-center gap-3">
            {isVeniceLoading ? (
              <Loader2 className="animate-spin text-purple-500" size={18} />
            ) : (
              <Cpu className="text-purple-500" size={18} />
            )}
            <div className="text-left">
              <div className="text-[11px] font-bold uppercase tracking-widest text-white">Venice: Make Sense of this Mess</div>
              <div className="text-[9px] font-mono text-white/40 uppercase mt-1 tracking-wider">Prune erronious data • Expand insights • Rebuild narrative</div>
            </div>
          </div>
          <ChevronRight className="text-white/20" size={16} />
        </button>
      </div>

      <div className="p-4 bg-white/5 border border-white/10 rounded-2xl">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/80">Auto-Expansion Engine</span>
          <div className="flex items-center gap-2">
             <span className="text-[8px] font-mono text-white/30 uppercase">Every 45s</span>
             <div 
               onClick={() => onToggleAutoGrow?.(!autoGrow)}
               className={`w-8 h-4 rounded-full relative cursor-pointer transition-colors ${autoGrow ? 'bg-green-500' : 'bg-white/10'}`}
             >
               <div className={`absolute top-0.5 w-3 h-3 bg-white rounded-full transition-all ${autoGrow ? 'right-0.5' : 'left-0.5'}`} />
             </div>
          </div>
        </div>
        <p className="text-[10px] font-mono text-white/40 uppercase leading-tight">
          When active, the engine autonomously scans for new connections periodically. Click the main "Expand" node in the graph for manual trigger.
        </p>
      </div>

      <div className="p-6 rounded-3xl bg-white/[0.02] border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <FlaskConical className="text-green-500/50" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/60">Hypothesis Stress-Test Lab</h3>
        </div>
        <p className="text-[10px] font-mono text-white/30 leading-relaxed uppercase">
          Propose a theory or outcome. The engine will look for evidence to confirm or debunk the logic.
        </p>
        <div className="flex flex-col gap-3">
          <textarea
            value={hypothesis}
            onChange={(e) => setHypothesis(e.target.value)}
            placeholder="e.g. 'Project X was used for money laundering via offshore accounts in jurisdiction Y'"
            className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-4 text-[11px] font-mono text-white/80 focus:border-green-500/50 focus:outline-none min-h-[80px] resize-none placeholder:text-white/10"
          />
          <button
            onClick={handleTestHypothesis}
            disabled={isTestingHypothesis || !hypothesis.trim()}
            className="flex items-center justify-center gap-2 py-3 rounded-xl bg-green-500 text-black text-[10px] font-bold uppercase tracking-widest hover:bg-green-400 active:scale-95 transition-all disabled:opacity-50"
          >
            {isTestingHypothesis ? (
              <Loader2 className="animate-spin" size={14} />
            ) : (
              <Microscope size={14} />
            )}
            Execute Stress Test
          </button>
        </div>
      </div>

      <AnimatePresence>
        {hypothesisResult && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="p-6 rounded-3xl bg-green-500/5 border border-green-500/20 space-y-4"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-green-500">
                <ShieldAlert size={14} />
                Stress Test Result
              </div>
              <button 
                onClick={() => setHypothesisResult(null)}
                className="text-[9px] font-mono uppercase text-white/30 hover:text-white"
              >
                Clear
              </button>
            </div>
            <div className="text-[11px] font-sans leading-relaxed text-white/70 prose prose-invert prose-xs max-h-[400px] overflow-y-auto custom-scrollbar">
              <ReactMarkdown>{hypothesisResult}</ReactMarkdown>
            </div>
          </motion.div>
        )}
        {error && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center gap-3 text-red-500 text-xs font-mono"
          >
            <AlertCircle size={14} />
            {error}
          </motion.div>
        )}
      </AnimatePresence>

      <div className="p-6 rounded-3xl bg-gradient-to-br from-white/[0.03] to-transparent border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <FileText className="text-white/20" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/40">Reporting Context</h3>
        </div>
        <p className="text-[10px] font-mono text-white/30 leading-relaxed uppercase tracking-tighter">
          Investigative reports are synthesized using real-time node heuristics. Grounding is provided by local lattice state and connected AI engines.
        </p>
      </div>
    </div>
  );
}
