import React, { useState } from 'react';
import { Download, ShieldAlert, FileText, Share2, Clipboard, Loader2, CheckCircle2, AlertCircle, Cpu, FlaskConical, Microscope, RotateCcw, ChevronRight, Wand2, FileDown } from 'lucide-react';
import { testHypothesis } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'motion/react';
import { buildLocalReport, buildSystemSuggestions, computeGraphMetrics, ReportMode } from '../lib/graphAnalytics';

interface ReportingDeckProps {
  graph: {
    nodes: any[];
    links: any[];
    narrative?: string;
  };
  projectName: string;
  onExpand?: () => void;
  isExpanding?: boolean;
  autoGrow?: boolean;
  onToggleAutoGrow?: (val: boolean) => void;
  handleDownloadBackup?: () => void;
  onVeniceSensemaking?: () => void;
  isVeniceLoading?: boolean;
}

export default function ReportingDeck({ graph, projectName, onExpand, isExpanding, autoGrow, onToggleAutoGrow, handleDownloadBackup, onVeniceSensemaking, isVeniceLoading }: ReportingDeckProps) {
  const [error, setError] = useState<string | null>(null);
  const [copySuccess, setCopySuccess] = useState(false);
  const [hypothesis, setHypothesis] = useState('');
  const [isTestingHypothesis, setIsTestingHypothesis] = useState(false);
  const [hypothesisResult, setHypothesisResult] = useState<string | null>(null);
  const [reportMode, setReportMode] = useState<ReportMode>('executive');
  const [localReport, setLocalReport] = useState<string | null>(null);

  if (!graph || !graph.nodes) {

  return (
      <div className="p-10 text-center opacity-20">
        <p className="text-[10px] font-mono uppercase">Initializing Intel Engine...</p>
      </div>
    );
  }

  const safeProjectName = projectName || 'Unnamed Investigation';
  const metrics = computeGraphMetrics(graph);
  const systemSuggestions = buildSystemSuggestions(graph);

  const exportToJson = () => {
    try {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(graph, null, 2));
      const downloadAnchorNode = document.createElement('a');
      downloadAnchorNode.setAttribute("href", dataStr);
      downloadAnchorNode.setAttribute("download", `${safeProjectName.replace(/\s+/g, '_')}_nexus_export.json`);
      document.body.appendChild(downloadAnchorNode);
      downloadAnchorNode.click();
      downloadAnchorNode.remove();
    } catch (err) {
      console.error("Export failed", err);
      setError("Failed to export JSON");
    }
  };

  const exportToCsv = () => {
    try {
      const headers = ['id', 'name', 'type', 'description'];
      const rows = (graph.nodes || []).map(n => [n.id, n.name || '', n.type || '', n.description || ''].map(v => `"${v}"`).join(','));
      const csvContent = "data:text/csv;charset=utf-8," + headers.join(',') + "\n" + rows.join('\n');
      const encodedUri = encodeURI(csvContent);
      const link = document.createElement("a");
      link.setAttribute("href", encodedUri);
      link.setAttribute("download", `${safeProjectName.replace(/\s+/g, '_')}_evidence_matrix.csv`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      console.error("CSV Export failed", err);
      setError("Failed to export CSV");
    }
  };

  const handleTestHypothesis = async () => {
    if (!hypothesis.trim()) return;
    setIsTestingHypothesis(true);
    setHypothesisResult(null);
    setError(null);
    try {
      const contextNodes = (graph.nodes || []).map(n => n.name || n.id);
      const result = await testHypothesis(hypothesis, contextNodes);
      setHypothesisResult(result);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsTestingHypothesis(false);
    }
  };

  const copyMarkdownDossier = () => {
    try {
      const md = `
# INVESTIGATIVE DOSSIER: ${safeProjectName}
## Intelligence Summary
${graph.narrative || 'No narrative generated.'}

## Entity Lattice
### Record (${(graph.nodes || []).length})
${(graph.nodes || []).map(n => `- **${n.name || n.id}** (${n.type}): ${n.description || 'No description available.'}`).join('\n')}

## Relationships (${(graph.links || []).length})
${(graph.links || []).map(l => `- ${l.source} → ${l.target} [${l.relationship || 'Connected'}]`).join('\n')}

---
**AUTHORITY: O'CROWLEY // NEXUS CORE**
*Generated by Nexus @ ${new Date().toISOString()}*
*Confidential ADR Intelligence Asset*
      `.trim();

      navigator.clipboard.writeText(md);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch (err) {
      console.error("Copy failed", err);
      setError("Failed to copy dossier");
    }
  };

  const generateLocalReport = () => {
    setLocalReport(buildLocalReport(graph, safeProjectName, reportMode));
  };

  const exportHtmlReport = () => {
    const report = localReport || buildLocalReport(graph, safeProjectName, reportMode);
    const escapedReport = report.replace(/[&<>]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[char] || char));
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${safeProjectName} Nexus Report</title><style>body{font-family:Inter,Arial,sans-serif;background:#050505;color:#f5f5f4;padding:40px;line-height:1.5}pre{white-space:pre-wrap;background:#111;padding:24px;border-radius:16px;border:1px solid #333}</style></head><body><pre>${escapedReport}</pre></body></html>`;
    const dataStr = 'data:text/html;charset=utf-8,' + encodeURIComponent(html);
    const link = document.createElement('a');
    link.setAttribute('href', dataStr);
    link.setAttribute('download', `${safeProjectName.replace(/\s+/g, '_')}_${reportMode}_report.html`);
    document.body.appendChild(link);
    link.click();
    link.remove();
  };

  return (
    <div className="space-y-6">
      <div className="grid grid-cols-2 gap-3">
        <button
          onClick={exportToJson}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/[0.03] border border-white/5 hover:bg-white/[0.08] transition-all hover:border-[#d4af37]/30 group"
        >
          <Share2 className="text-white/40 group-hover:text-[#d4af37] mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">JSON Export</span>
        </button>

        <button
          onClick={exportToCsv}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/[0.03] border border-white/5 hover:bg-white/[0.08] transition-all hover:border-[#d4af37]/30 group"
        >
          <Download className="text-white/40 group-hover:text-[#d4af37] mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">CSV Matrix</span>
        </button>

        <button
          onClick={copyMarkdownDossier}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-white/[0.03] border border-white/5 hover:bg-white/[0.08] transition-all hover:border-[#d4af37]/30 group"
        >
          {copySuccess ? (
            <CheckCircle2 className="text-[#d4af37] mb-2" size={20} />
          ) : (
            <Clipboard className="text-white/40 group-hover:text-[#d4af37] mb-2" size={20} />
          )}
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/40 group-hover:text-white transition-colors">MD Dossier</span>
        </button>

        <button
          onClick={handleDownloadBackup}
          className="flex flex-col items-center justify-center p-4 rounded-2xl bg-[#d4af37]/10 border border-[#d4af37]/20 hover:bg-[#d4af37]/20 transition-all hover:border-[#d4af37] group"
        >
          <RotateCcw className="text-[#d4af37] mb-2" size={20} />
          <span className="text-[10px] font-bold uppercase tracking-widest text-[#d4af37]">Local Archive</span>
        </button>
      </div>

      <div className="grid grid-cols-4 gap-2">
        <div className="rounded-2xl bg-white/5 border border-white/5 p-3">
          <div className="text-xl font-black text-white">{metrics.nodeCount}</div>
          <div className="text-[8px] font-mono uppercase text-white/40">Entities</div>
        </div>
        <div className="rounded-2xl bg-white/5 border border-white/5 p-3">
          <div className="text-xl font-black text-white">{metrics.linkCount}</div>
          <div className="text-[8px] font-mono uppercase text-white/40">Links</div>
        </div>
        <div className="rounded-2xl bg-white/5 border border-white/5 p-3">
          <div className="text-xl font-black text-white">{metrics.isolatedCount}</div>
          <div className="text-[8px] font-mono uppercase text-white/40">Isolates</div>
        </div>
        <div className="rounded-2xl bg-white/5 border border-white/5 p-3">
          <div className="text-xl font-black text-white">{metrics.sourceBackedCount}</div>
          <div className="text-[8px] font-mono uppercase text-white/40">Evidence</div>
        </div>
      </div>

      <div className="p-5 rounded-3xl bg-white/[0.02] border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <Wand2 className="text-[#d4af37]/70" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/60">Reporting Mode Builder</h3>
        </div>
        <div className="grid grid-cols-2 gap-2">
          {(['executive', 'evidence', 'gaps', 'technical'] as ReportMode[]).map(mode => (
            <button
              key={mode}
              onClick={() => setReportMode(mode)}
              className={`rounded-xl border p-3 text-[9px] font-bold uppercase tracking-widest transition-all ${reportMode === mode ? 'border-[#d4af37]/40 bg-[#d4af37]/10 text-[#d4af37]' : 'border-white/5 bg-white/5 text-white/40 hover:text-white'}`}
            >
              {mode}
            </button>
          ))}
        </div>
        <div className="grid grid-cols-2 gap-2">
          <button onClick={generateLocalReport} className="flex items-center justify-center gap-2 rounded-xl bg-[#d4af37] px-3 py-3 text-[9px] font-bold uppercase tracking-widest text-black hover:bg-[#eab308]">
            <FileText size={13} /> Generate
          </button>
          <button onClick={exportHtmlReport} className="flex items-center justify-center gap-2 rounded-xl border border-white/5 bg-white/5 px-3 py-3 text-[9px] font-bold uppercase tracking-widest text-white/50 hover:text-[#d4af37]">
            <FileDown size={13} /> HTML Report
          </button>
        </div>
      </div>

      <div className="p-1 rounded-2xl bg-gradient-to-r from-blue-600/20 via-purple-600/20 to-green-600/20 relative overflow-hidden group">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-500/10 via-purple-500/10 to-green-500/10 opacity-0 group-hover:opacity-100 transition-opacity" />
        <button
          onClick={onVeniceSensemaking}
          disabled={isVeniceLoading}
          className="w-full relative flex items-center justify-between p-4 bg-[#0a0a0a] rounded-xl border border-white/5 hover:border-white/10 transition-colors disabled:opacity-50"
        >
          <div className="flex items-center gap-3">
            {isVeniceLoading ? (
              <Loader2 className="animate-spin text-purple-500" size={18} />
            ) : (
              <Cpu className="text-purple-500" size={18} />
            )}
            <div className="text-left">
              <div className="text-[11px] font-bold uppercase tracking-widest text-white">Venice: Make Sense of this Mess</div>
              <div className="text-[9px] font-mono text-white/40 uppercase mt-1 tracking-wider">Prune erronious data • Expand insights • Rebuild narrative</div>
            </div>
          </div>
          <ChevronRight className="text-white/20" size={16} />
        </button>
      </div>

      <div className="p-4 bg-white/5 border border-white/10 rounded-2xl">
        <div className="flex items-center justify-between mb-2">
          <span className="text-[10px] font-bold uppercase tracking-widest text-white/80">Auto-Expansion Engine</span>
          <div className="flex items-center gap-2">
             <span className="text-[8px] font-mono text-white/30 uppercase">Every 45s</span>
             <div
               onClick={() => onToggleAutoGrow?.(!autoGrow)}
               className={`w-8 h-4 rounded-full relative cursor-pointer transition-colors ${autoGrow ? 'bg-[#d4af37]' : 'bg-white/10'}`}
             >
               <div className={`absolute top-0.5 w-3 h-3 bg-white rounded-full transition-all ${autoGrow ? 'right-0.5' : 'left-0.5'}`} />
             </div>
          </div>
        </div>
        <p className="text-[10px] font-mono text-white/40 uppercase leading-tight">
          When active, the engine autonomously scans for new connections periodically. Click the main "Expand" node in the graph for manual trigger.
        </p>
      </div>

      <div className="p-6 rounded-3xl bg-white/[0.02] border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <FlaskConical className="text-[#d4af37]/50" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/60">Hypothesis Stress-Test Lab</h3>
        </div>
        <p className="text-[10px] font-mono text-white/30 leading-relaxed uppercase">
          Propose a theory or outcome. The engine will look for evidence to confirm or debunk the logic.
        </p>
        <div className="flex flex-col gap-3">
          <textarea
            value={hypothesis}
            onChange={(e) => setHypothesis(e.target.value)}
            placeholder="e.g. 'Project X was used for money laundering via offshore accounts in jurisdiction Y'"
            className="w-full bg-[#0a0a0a] border border-white/5 rounded-xl p-4 text-[11px] font-mono text-white/80 focus:border-[#d4af37]/50 focus:outline-none min-h-[80px] resize-none placeholder:text-white/10"
          />
          <button
            onClick={handleTestHypothesis}
            disabled={isTestingHypothesis || !hypothesis.trim()}
            className="flex items-center justify-center gap-2 py-3 rounded-xl bg-[#d4af37] text-black text-[10px] font-bold uppercase tracking-widest hover:bg-[#eab308] active:scale-95 transition-all disabled:opacity-50"
          >
            {isTestingHypothesis ? (
              <Loader2 className="animate-spin" size={14} />
            ) : (
              <Microscope size={14} />
            )}
            Execute Stress Test
          </button>
        </div>
      </div>

      <AnimatePresence>
        {localReport && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="p-6 rounded-3xl bg-[#d4af37]/5 border border-[#d4af37]/20 space-y-4"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-[#d4af37]">
                <FileText size={14} />
                {reportMode} Report
              </div>
              <button onClick={() => setLocalReport(null)} className="text-[9px] font-mono uppercase text-white/30 hover:text-white">Clear</button>
            </div>
            <pre className="max-h-[420px] overflow-y-auto custom-scrollbar whitespace-pre-wrap text-[11px] leading-relaxed text-white/70">{localReport}</pre>
          </motion.div>
        )}
        {hypothesisResult && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="p-6 rounded-3xl bg-green-500/5 border border-green-500/20 space-y-4"
          >
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.2em] text-green-500">
                <ShieldAlert size={14} />
                Stress Test Result
              </div>
              <button
                onClick={() => setHypothesisResult(null)}
                className="text-[9px] font-mono uppercase text-white/30 hover:text-white"
              >
                Clear
              </button>
            </div>
            <div className="text-[11px] font-sans leading-relaxed text-white/70 prose prose-invert prose-xs max-h-[400px] overflow-y-auto custom-scrollbar">
              <ReactMarkdown>{hypothesisResult}</ReactMarkdown>
            </div>
          </motion.div>
        )}
        {error && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 flex items-center gap-3 text-red-500 text-xs font-mono"
          >
            <AlertCircle size={14} />
            {error}
          </motion.div>
        )}
      </AnimatePresence>

      <div className="p-6 rounded-3xl bg-white/[0.02] border border-white/5 space-y-3">
        <div className="flex items-center gap-3">
          <ShieldAlert className="text-[#d4af37]/50" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/50">System Suggestions</h3>
        </div>
        {systemSuggestions.map((suggestion, index) => (
          <div key={index} className="rounded-xl border border-white/5 bg-black/20 p-3 text-[10px] font-mono uppercase leading-relaxed text-white/40">{suggestion}</div>
        ))}
      </div>

      <div className="p-6 rounded-3xl bg-gradient-to-br from-white/[0.03] to-transparent border border-white/5 space-y-4">
        <div className="flex items-center gap-3">
          <FileText className="text-white/20" size={18} />
          <h3 className="text-[10px] font-bold uppercase tracking-widest text-white/40">Reporting Context</h3>
        </div>
        <p className="text-[10px] font-mono text-white/30 leading-relaxed uppercase tracking-tighter">
          Investigative reports are synthesized using real-time node heuristics. Grounding is provided by local lattice state and connected AI engines.
        </p>
      </div>
    </div>
  );
}
